.PHONY: build validate audit eval site graph track synthesize recap-dry check help

help:
	@echo "longevity-loop — an AI-native compounding loop for aging science"
	@echo "  make build       Regenerate README.md + docs/ROADMAP.md from data/*.yml"
	@echo "  make validate    Schema-gate data/*.yml"
	@echo "  make audit       Self-audit vs the AI-native loop principles (data/loop.yml)"
	@echo "  make track       Refresh live arXiv/GitHub signal into data/_frontier.yml"
	@echo "  make synthesize  Draft frontier+roadmap proposals into data/_synthesis.md (human-gated)"
	@echo "  make check       validate + audit + eval + build drift-gate (CI finish line)"

build:
	python3 scripts/build.py

validate:
	python3 scripts/validate.py

audit:
	python3 scripts/audit.py --gate 80

# Roadmap checkbox + before→after eval; fails if a `done` item has no real eval.
eval:
	python3 scripts/eval.py --gate

site:
	python3 scripts/build_site.py
	python3 scripts/build_graph.py

graph:
	python3 scripts/build_graph.py

# Refresh live frontier signal (arXiv + GitHub) into data/_frontier.yml (needs network).
track:
	python3 scripts/track.py

# Draft frontier-update + roadmap-delta PROPOSALS (Europe PMC) into data/_synthesis.md.
# Human-gated: never edits frontier.yml/roadmap.yml — a person promotes what's real.
synthesize:
	python3 scripts/synthesize.py

# Preview the daily recap offline (no API key, no tokens) — proves the pipeline.
# The real article is generated by the daily `recap` GitHub Actions cron.
recap-dry:
	python3 scripts/recap.py --since HEAD~3 --dry-run

# Finish line: data well-formed, still an AI-native loop, executions honestly
# eval'd (no fake ✅), and generated docs match.
check: validate audit eval
	python3 scripts/build.py --check
